### ISSUE TITLE
好东西 谢谢作者

### ISSUE THREAD

**Issue by Jameshuang8045** [frederick-wang/scu-urp-assistant#13]

**Comment by frederick-wang** [comment]
哈哈，能帮到同学们我就很开心啦\~谢谢你的认可\~

**Comment by Jameshuang8045** [comment]
学长你还在川大读吗






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhaoji Wang"<notifications@github.com&gt;; 
发送时间: 2020年6月11日(星期四) 晚上8:10
收件人: "frederick-wang/scu-urp-assistant"<scu-urp-assistant@noreply.github.com&gt;; 
抄送: "爿"<2535538045@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [frederick-wang/scu-urp-assistant] 好东西 谢谢作者 (#13)





 
哈哈，能帮到同学们我就很开心啦谢谢你的认可

**Comment by frederick-wang** [comment]
> 学长你还在川大读吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Zhaoji Wang"<notifications@github.com&gt;; 发送时间: 2020年6月11日(星期四) 晚上8:10 收件人: "frederick-wang/scu-urp-assistant"<scu-urp-assistant@noreply.github.com&gt;; 抄送: "爿"<2535538045@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [frederick-wang/scu-urp-assistant] 好东西 谢谢作者 (#13) 哈哈，能帮到同学们我就很开心啦谢谢你的认可 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯，我是2017级的，现在还在校。
