### ISSUE TITLE
Export class timetable as a wallpaper

### ISSUE THREAD

**Issue by ghost** [frederick-wang/scu-urp-assistant#3]
It's just an idea. I'm not sure how many stu take a screenshot, as lock screen image on phone, which is unclear and bad looking.

And here is it  -  support saving image with different scales (3:4, 9:19, etc) in higher resolution and briefer words than screenshots.

I know it's time-consuming to implement so just an idea.

**Comment by frederick-wang** [comment]
Sorry, I missed this issue. Obviously that's an interesting idea. I will consider adding this feature in future releases.
