### ISSUE TITLE
0.12.3版本在violent monkey上无法使用

### ISSUE THREAD

**Issue by hybcloud** [frederick-wang/scu-urp-assistant#53]
violent monkey认为该脚本非法，但tamper monkey则能够接受。好像不是什么大问题。

**Comment by frederick-wang** [comment]
请问之前的版本在 `Violent Monkey` 上可以正常使用吗……？

**Comment by hybcloud** [comment]
啊，刚才测试了一下，就算是`0.10.1`版本也不行。如果您测试出来的结果也是这样，要不要在`Greasy Fork`上说明一下不能用`Violent Monkey`？

**Comment by frederick-wang** [comment]
我试了试，在我的 Chrome 上暴力猴弹不出来安装界面，我之后在 Greasy Fork 上补一句说明，为了保证兼容性，请使用 Tamper Monkey。
