### ISSUE TITLE
版本迭代的问题

### ISSUE THREAD

**Issue by xxxVincent-L** [frederick-wang/scu-urp-assistant#62]
单纯地好奇，我之前的是0.13.1的版本用不了（这里的版本我是在Tampermonkey中看到的），降格到0.13.0才能够正常使用。但我在您的博客中看到，0.13.0已经是最新版本了。所以有点迷糊orz

**Comment by frederick-wang** [comment]
没有更新过 `v0.13.1` 版本，目前最新版本即为 `v0.13.0`。
