### ISSUE TITLE
选定教材加一个全选/全不选的开关

### ISSUE THREAD

**Issue by ghost** [frederick-wang/scu-urp-assistant#9]
选定教材一个一个点比较麻烦，加一个 全部选中/全部不选 的按钮会很贴心。
应该没有触及卖书人的利益吧 ( >﹏<。)

**Comment by frederick-wang** [comment]
现在正选阶段已经结束了，打不开选教材界面了，下次开放时可以考虑。

**Comment by frederick-wang** [comment]
> 现在正选阶段已经结束了，打不开选教材界面了，下次开放时可以考虑。

目前已经增加了这个功能，将在0.10.3版本中启用。
